version: '3.7'

services:
  hydra-migrate:
    environment:
      - DSN=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@hydra-postgresd:5432/${DATABASE_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - hydra_data:/var/lib/postgresql/data

  hydra:
    environment:
      - DSN=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@hydra-postgresd:5432/${DATABASE_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - hydra_data:/var/lib/postgresql/data

  hydra-postgresd:
    image: postgres:9.6
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    networks:
      - intranet

networks:
  intranet:
    name: fantom-identity

volumes:
  hydra_data: