version: '3.7'

services:

  hydra-migrate:
    image: oryd/hydra:v1.8.5
    command:
      migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  hydra:
    image: oryd/hydra:v1.8.5
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    depends_on:
      - hydra-migrate
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_SELF_PUBLIC=http://127.0.0.1:4444
      - URLS_CONSENT=http://127.0.0.1:3000/auth/consent
      - URLS_LOGIN=http://127.0.0.1:3000/auth/login
      - URLS_LOGOUT=http://127.0.0.1:3000/auth/logout
      - DSN=memory
      - SECRETS_SYSTEM=fantomIdentitySecret
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=fantomIdentitySalt
      - LOG_LEAK_SENSITIVE_VALUES=true
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=true
    restart: unless-stopped
    networks:
      - intranet

networks:
  intranet:
    name: fantom-identity